//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocioDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCuidado
    {
        public int IdPlanCuidado { get; set; }
        public int IdAnimal { get; set; }
        public int IdCuidador { get; set; }
        public byte DiaSemana { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Cuidador Cuidador { get; set; }
    }
}
